### ISSUE TITLE
Setup language bug

### ISSUE THREAD

**Issue by neebooo** [LuminaryOS-Project/LuminaryOS#6]
**Description:**
The installer doesn't download the language packs necessary to launch the OS 

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Part of OS:**
- [x] Main
- [ ] Setup
- [ ] Recovery

**Tools version:**

1.1 BETA
**Repro steps:**  
Launch the jar without the LuminaryOS Folder

**Expected behavior:**
The installer should download the english lang pack

**Actual behavior:**
The installer doesn't do it and as it finishes its setup the program crashes with this error:
```
Couldn't find default language, defaulting to english.
Exception in thread "main" com.luminary.os.core.exceptions.InvalidLanguageException: Specified Language does not exist.
        at com.luminary.os.core.Language.<init>(Language.java:15)
        at com.luminary.os.OS.Start(OS.java:86)
        at com.luminary.os.Start.main(Start.java:104)
```

**Comment by Intel-Projects** [comment]
Fixed in commit fix #a98b815
